### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by arievanoosten** [mvdnes/esphome-otgw#1]
Hello, 
Maybe I'm not putting it in the right place. But I can't get my configuration validated. I put the folder "otgw" in the folder "esphome" and added your code to an existing config. But I get the following message with validation:
otgw: [source /config/esphome/zolder.yaml:125]

Component not found: otgw.
uart_id: uart_otgw

Can you tell me what I'm doing wrong?

**Comment by mvdnes** [comment]
I have updated the folder structure of this repository to include the 'components' directory.
Can you test it again, by adding the following to your code?
```yaml
external_components:
  - source: github://mvdnes/esphome-otgw
```

If you already tried this you may need to temporarily add a refresh to it to ensure the repository is up-to-date:


```yaml
external_components:
  - source: github://mvdnes/esphome-otgw
    refresh: 0s
```

**Comment by arievanoosten** [comment]
Thank you, that was the solution indeed
